### ISSUE TITLE
Module __FreeCAD_Base__ has no attribute precision

### ISSUE THREAD

**Issue by mikeq3** [tomate44/CurvesWB#119]
When I select the Curves Workbench for the first time after starting FreeCAD, I see the error: 
"Module '__FreeCAD_Base__' has no attribute precision"
Also, I am not seeing the toolbar for this workbench most likely due to the error.
I'm running on Fedora linux and using FreeCAD version 0.20.2
This is after installing the workbench from the add on manager in FreeCAD.

Here is the error log display:
11:46:53  module '__FreeCADBase__' has no attribute 'Precision'
11:46:53  Traceback (most recent call last):
  File "/home/mikeq/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/init_gui.py", line 38, in Initialize
    from . import IsoCurve
  File "/usr/lib64/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/mikeq/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/IsoCurve.py", line 22, in <module>
    from freecad.Curves import isocurves
  File "/usr/lib64/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/mikeq/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/isocurves.py", line 19, in <module>
    TOL3D = FreeCAD.Base.Precision.confusion()

It is having a problem with calling this function: FreeCAD.Base.Precision.confusion()
If I change the line to: TOL3D = 10000000 it does not error.

**Comment by tomate44** [comment]
It should be fixed in version 0.6.33
Can you please confirm ( I am not able to test in FreeCAD 0.20.2 ) ?

**Comment by mikeq3** [comment]
Sorry I just saw this. I just updated to 0.6.35 and it looks good so far in FreeCad 0.20.2
