### ISSUE TITLE
Segment a surface function not working in 0.22.0dev

### ISSUE THREAD

**Issue by FieteO** [tomate44/CurvesWB#129]
Clicking on the `Segment a surface` button fails with the following stack trace:
```
16:47:24  Running the Python command 'segment_surface' failed:
Traceback (most recent call last):
  File "/home/fiete/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/segmentSurfaceFP.py", line 208, in Activated
    self.makeFeature(sel[0])
  File "/home/fiete/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/segmentSurfaceFP.py", line 199, in makeFeature
    SegmentSurface(fp, (s.Object, s.SubElementNames[0]))
                                  ~~~~~~~~~~~~~~~~~^^^

tuple index out of rangeRunning the Python command 'segment_surface' failed:
Traceback (most recent call last):
  File "/home/fiete/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/segmentSurfaceFP.py", line 208, in Activated
    self.makeFeature(sel[0])
  File "/home/fiete/.local/share/FreeCAD/Mod/Curves/./freecad/Curves/segmentSurfaceFP.py", line 199, in makeFeature
    SegmentSurface(fp, (s.Object, s.SubElementNames[0]))
                                  ~~~~~~~~~~~~~~~~~^^^
```
This occurs with the latest dev build: ` FreeCAD_weekly-builds-38429-conda-Linux-x86_64-py311.AppImage `

**Comment by tomate44** [comment]
I think you selected the object in the Tree View.
The tooltip of Segment Surface says : "Select a face in the **3D View**
