### ISSUE TITLE
Segmentation fault while extruding mapped sketch

### ISSUE THREAD

**Issue by kalbfuss** [tomate44/CurvesWB#140]
Freecad produces a segmentation fault, when I attempt to extrude the "Sketch_on_Surface" in the file enclosed with "Fill Extrusion" and "Fill Faces" enabled. Filling faces without extrusion works fine.

The error occurs with the Ubuntu Freecad v1.0 snap and the latest freecad-daily from 26-Dec-2026.

This is is the error message I receive on the command line:

```
Sketch bounds = (0.0, 138.98563799423508, 0.0, 127.07516239235011)
Target face bounds = (0.9332475286562036, 2.2083451249335897, -0.5829135889557342, 0.5829135889557345)
mapping shape #  1
Invalid imbrication of wires

 42:Invalid initial face
 42:Invalid final faceInvalid imbrication of wires

 98:Invalid initial face
 98:Invalid final faceInvalid imbrication of wires

100:Invalid initial face
100:Invalid final faceTotal : 155 shapes
mapping shape #  1
Invalid imbrication of wires

 42:Invalid initial face
 42:Invalid final faceInvalid imbrication of wires

 98:Invalid initial face
 98:Invalid final faceInvalid imbrication of wires

100:Invalid initial face
100:Invalid final faceTotal : 155 shapes
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x7208eb245320]
#1  0x7208a9fd92d4 in BRepFill::Face(TopoDS_Edge const&, TopoDS_Edge const&) from /lib/x86_64-linux-gnu/libTKBool.so.7.8+0x1d4
#2  0x7208b487cc91 in Part::TopoShape::makeElementRuledSurface(std::vector<Part::TopoShape, std::allocator<Part::TopoShape> > const&, int, char const*) from /usr/lib/freecad-daily-python3/lib/Part.so+0x521
#3  0x7208b47e2ec4 in Part::Module::makeRuledSurface(Py::Tuple const&, Py::Dict const&) from /usr/lib/freecad-daily-python3/lib/Part.so+0x1e4
#4  /usr/lib/freecad-daily-python3/lib/Part.so(+0x3d406b) [0x7208b47d406b]
#5  /usr/lib/freecad-daily-python3/lib/libFreeCADBase.so(method_keyword_call_handler+0x3c4) [0x7208edac48a4]
#6  /lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x1dbe88) [0x7208ed1dbe88]
#7  /lib/x86_64-linux-gnu/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x8f) [0x7208ed1827af]
#8  /lib/x86_64-linux-gnu/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x40ee) [0x7208ed11d5ee]
#9  /lib/x86_64-linux-gnu/libpython3.12.so.1.0(+0x18604d) [0x7208ed18604d]
#10  /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so(+0x22fe19) [0x7208ee02fe19]
#11  0x7208ee06953e in App::FeaturePythonImp::execute() from /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so+0xfe
#12  0x7208b467dbda in App::FeaturePythonT<Part::Feature>::execute() from /usr/lib/freecad-daily-python3/lib/Part.so+0x1a
#13  0x7208edffa024 in App::DocumentObject::recompute() from /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so+0x44
#14  0x7208b4672f90 in Part::Feature::recompute() from /usr/lib/freecad-daily-python3/lib/Part.so+0x10
#15  0x7208edfb760c in App::Document::_recomputeFeature(App::DocumentObject*) from /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so+0x26c
#16  0x7208edfb455e in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so+0x5fe
#17  0x7208eeb92fa2 in Gui::PropertyEditor::PropertyEditor::recomputeDocument(App::Document*) from /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so+0x82
#18  0x7208eeb93074 in Gui::PropertyEditor::PropertyEditor::closeTransaction() from /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so+0x94
#19  0x7208eeb968c0 in Gui::PropertyEditor::PropertyEditor::closeEditor(QWidget*, QAbstractItemDelegate::EndEditHint) from /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so+0x50
#20  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x312dbf) [0x7208ebd12dbf]
#21  0x7208ecc17c49 in QAbstractItemDelegate::closeEditor(QWidget*, QAbstractItemDelegate::EndEditHint) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x59
#22  0x7208ebd06343 in QObject::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x293
#23  0x7208ec96bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x85
#24  0x7208ee8f87a8 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so+0xd8
#25  0x7208ebcd8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x128
#26  0x7208ebcdb94b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x19b
#27  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x335c0f) [0x7208ebd35c0f]
#28  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5d5b5) [0x7208e9f145b5]
#29  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbc717) [0x7208e9f73717]
#30  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7208e9f13a53]
#31  0x7208ebd35279 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x69
#32  0x7208ebcd6a7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x13b
#33  0x7208ebcdf3e8 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x98
#34  0x7208ee871725 in Gui::Application::runApplication() from /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so+0x8c5
#35  freecad-daily(+0x607b) [0x57d4ddf1707b]
#36  /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x7208eb22a1ca]
#37  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7208eb22a28b]
#38  freecad-daily(+0x7285) [0x57d4ddf18285]
```
And this is the file, which produces the segmentation fault:
[Runde Schatulle mit Gravur 4.zip](https://github.com/user-attachments/files/18253617/Runde.Schatulle.mit.Gravur.4.zip)

**Comment by luzpaz** [comment]
Can you add your full [About](https://wiki.freecad.org/About) info ?
